const tabs=[['dashboard','⌂','总览'],['bills','¥','账单'],['tasks','✓','值日'],['inventory','▣','物品'],['visitors','♙','访客'],['safety','⌾','安全'],['rules','§','公约'],['audit','≡','档案'],['settings','⚙','设置']];
const seed={
bills:[{id:'PAY-260915-01',name:'9月房租',amount:6000,due:'2026-09-15',payer:'小王',status:'待缴费',repeat:'每月15日',remind:'提前7天、3天'},{id:'PAY-260920-02',name:'9月燃气费',amount:120,due:'2026-09-20',payer:'小林',status:'待缴费',repeat:'每月20日',remind:'提前3天'},{id:'PAY-260910-03',name:'8月电费',amount:326.4,due:'2026-09-10',payer:'小王',status:'已垫付',repeat:'每月',remind:'已提醒3次'},{id:'PAY-260901-04',name:'宽带费',amount:396,due:'2026-09-01',payer:'阿杰',status:'已结清',repeat:'每季度',remind:'已完成'}],
tasks:[{id:'TSK-0912-01',date:'今天',name:'厨房清洁',owner:'小林',time:'21:00前',status:'待处理'},{id:'TSK-0913-02',date:'周日',name:'卫生间清洁',owner:'阿杰',time:'20:00前',status:'已排班'},{id:'TSK-0913-03',date:'周日',name:'采购抽纸',owner:'小王',time:'18:00前',status:'待接收'},{id:'TSK-0911-04',date:'昨天',name:'客厅吸尘',owner:'小陈',time:'已于20:16完成',status:'已验收'}],
stock:[{id:'STK-01',icon:'🧻',name:'抽纸',qty:2,unit:'包',min:4},{id:'STK-02',icon:'🗑️',name:'垃圾袋',qty:3,unit:'卷',min:3},{id:'STK-03',icon:'🧴',name:'洗手液',qty:5,unit:'瓶',min:2},{id:'STK-04',icon:'🧽',name:'清洁海绵',qty:4,unit:'块',min:2}],
shopping:[{name:'抽纸 6包',owner:'小王',status:'待采购'}],
visitors:[{id:'VIS-0916-01',host:'小林',guest:'父母',count:2,start:'9月16日 18:00',end:'9月18日 10:00',stay:'留宿2晚',status:'待确认',conflict:'9月16日晚与客厅聚会预约冲突'},{id:'VIS-0908-02',host:'阿杰',guest:'同学',count:1,start:'9月8日 19:00',end:'当日 22:00',stay:'不留宿',status:'已结束',conflict:''}],
safety:[{name:'小王',time:'22:30',status:'预计按时'},{name:'小林',time:'22:00',status:'已到家'},{name:'小陈',time:'00:30',status:'已报备晚归'},{name:'阿杰',time:'—',status:'今晚不回'}],
rules:[{id:'RUL-01',title:'访客须提前24小时报备',detail:'多人或连续留宿需全体确认',status:'已生效'},{id:'RUL-02',title:'23:00后保持安静',detail:'公共区域降低音量，晚归避免打扰',status:'已生效'},{id:'RUL-03',title:'访客额外费用归属',detail:'连续留宿超过3天，邀请人额外承担当月水电10%',status:'待阿杰确认'}],
logs:[{code:'PAY-202609-0018',type:'账单',time:'今天 20:36',who:'小王',action:'上传缴费凭证',detail:'8月电费 ¥326.40，已生成AA分摊'},{code:'TSK-202609-0032',type:'任务',time:'今天 20:12',who:'小林',action:'提交任务完成',detail:'厨房清洁，等待室友验收'},{code:'STK-202609-0011',type:'物品',time:'今天 19:45',who:'小陈',action:'登记物品消耗',detail:'抽纸 -1包，当前剩余2包'},{code:'VIS-202609-0006',type:'访客',time:'今天 18:30',who:'阿杰',action:'确认访客申请',detail:'小林父母留宿申请'},{code:'RUL-202608-0003',type:'公约',time:'8月21日 21:10',who:'全体成员',action:'公约版本生效',detail:'室友公约 v2.1'}]};
let data=JSON.parse(localStorage.getItem('roomie_mvp_v2')||'null')||structuredClone(seed);
let currentUser=localStorage.getItem('roomie_user')||'';
data.members ||= [{name:'小王',role:'房屋管理员',room:'主卧'},{name:'小林',role:'普通成员',room:'次卧A'},{name:'小陈',role:'普通成员',room:'次卧B'},{name:'阿杰',role:'普通成员',room:'书房'}];
data.preferences ||= {city:'上海·浦东',billReminder:'提前7天、3天',safetyTime:'23:30'};
data.bills.forEach(b=>b.shares||=data.members.map(m=>({name:m.name,amount:+(b.amount/data.members.length).toFixed(2),paid:b.status==='已结清'})));
function save(){localStorage.setItem('roomie_mvp_v2',JSON.stringify(data))}
function init(){today.textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(new Date());nav.innerHTML=tabs.map((t,i)=>`<button class="${i?'':'active'}" onclick="go('${t[0]}')"><b>${t[1]}</b>${t[2]}</button>`).join('');mobileNav.innerHTML=tabs.slice(0,6).map(t=>`<button onclick="go('${t[0]}')"><b>${t[1]}</b>${t[2]}</button>`).join('');if(currentUser)applyIdentity();renderAll()}
function selectIdentity(name){if(houseCode.value.trim().toUpperCase()!=='HUPO2026')return notify('邀请码不正确');currentUser=name;localStorage.setItem('roomie_user',name);applyIdentity();identityGate.classList.add('hidden');audit('安全','确认登录身份',`${name}进入湖畔小屋`)}
function applyIdentity(){identityGate.classList.add('hidden');userName.textContent=currentUser;userAvatar.textContent=currentUser.slice(-1);userRole.textContent=currentUser==='小王'?'房屋管理员':'普通成员';let due={小王:1581.6,小林:1581.6,小陈:1581.6,阿杰:1499.2};dueTotal.textContent='¥'+due[currentUser].toFixed(2)}
function switchIdentity(){identityGate.classList.remove('hidden')}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach((x,i)=>x.classList.toggle('active',tabs[i][0]===id));pageTitle.textContent=tabs.find(x=>x[0]===id)[2]+(id==='dashboard'?'总览':'管理');scrollTo(0,0)}
const badge=s=>`<span class="pill ${s.includes('待')||s.includes('晚归')?'orange':'green'}">${s}</span>`;
function row(title,sub,right){return `<div class="row"><div><strong>${title}</strong><small>${sub}</small></div><div>${right}</div></div>`}
function renderAll(){renderDashboard();renderBills();renderTasks();renderStock();renderVisitors();renderSafety();renderRules();renderLogs();renderSettings()}
function renderDashboard(){dashboardBills.innerHTML=data.bills.slice(0,3).map(b=>row(b.name,`${b.due} 到期 · ${b.payer}负责`,`<span class="amount">¥${Number(b.amount).toFixed(2)}</span><br>${badge(b.status)}`)).join('');dashboardSafety.innerHTML=data.safety.map(s=>row(s.name,`预计 ${s.time}`,badge(s.status))).join('');dashboardTasks.innerHTML=data.tasks.slice(0,3).map(t=>row(t.name,`${t.date} · ${t.owner}`,badge(t.status))).join('');dashboardStock.innerHTML=data.stock.slice(0,3).map(s=>row(`${s.icon} ${s.name}`,`剩余 ${s.qty}${s.unit}`,s.qty<=s.min?badge('库存偏低'):badge('充足'))).join('');let v=data.visitors[0];dashboardVisitor.innerHTML=`<h3>${v.host}的${v.guest} · ${v.count}人</h3><small>${v.start}—${v.end} · ${v.stay}</small><p>${badge(v.status)}</p><small>${v.conflict}</small>`;dashboardLogs.innerHTML=data.logs.slice(0,3).map(l=>`<div class="activity"><b>${l.who} · ${l.action}</b><small>${l.time}</small><small>${l.detail}</small></div>`).join('');lowStockCount.textContent=data.stock.filter(s=>s.qty<=s.min).length+' 项';safeCount.textContent=data.safety.filter(s=>['已到家','今晚不回','已报备晚归'].includes(s.status)).length+' / '+data.safety.length}
function renderBills(){let f=billFilter?.value||'全部状态',list=f==='全部状态'?data.bills:data.bills.filter(b=>b.status===f);billList.innerHTML=list.map(b=>row(b.name,`${b.id} · ${b.due}到期 · ${b.repeat} · ${b.remind}${b.proof?' · 凭证 '+b.proof:''}`,`<div class="action-group"><span class="amount">¥${Number(b.amount).toFixed(2)}</span>${badge(b.status)}<button class="mini" onclick="editBill('${b.id}')">编辑</button><button class="mini" onclick="billDetail('${b.id}')">明细</button>${b.status==='待缴费'?`<button class="mini" onclick="payBill('${b.id}')">缴费</button>`:b.status==='已垫付'?`<button class="mini" onclick="settleBill('${b.id}')">结清</button>`:''}</div>`)).join('')}
function renderTasks(){let days=['周一','周二','周三','周四','周五','今天','周日'];weekBoard.innerHTML=days.map((d,i)=>`<div class="day ${d==='今天'?'today':''}"><b>${d}</b><small>${7+i}日</small>${data.tasks.filter(t=>t.date===d).map(t=>`<div class="task-chip">${t.name}<br><small>${t.owner}</small></div>`).join('')}</div>`).join('');taskList.innerHTML=data.tasks.map(t=>row(t.name,`${t.id} · ${t.date} ${t.time} · 负责人 ${t.owner}${t.proof?' · 证明 '+t.proof:''}`,`<div class="action-group">${badge(t.status)}<button class="mini" onclick="editTask('${t.id}')">编辑</button><button class="mini" onclick="swapTask('${t.id}')">调班</button>${t.status==='待处理'?`<button class="mini" onclick="finishTask('${t.id}')">提交完成</button>`:t.status==='待验收'?`<button class="mini" onclick="verifyTask('${t.id}')">验收</button>`:''}</div>`)).join('')}
function renderStock(){stockGrid.innerHTML=data.stock.map(s=>`<div class="stock-card"><div class="stock-icon">${s.icon}</div><h3>${s.name}</h3><small>当前 ${s.qty}${s.unit} · 安全库存 ${s.min}${s.unit}</small><div class="bar ${s.qty<=s.min?'low':''}"><i style="width:${Math.min(100,s.qty/(s.min*2)*100)}%"></i></div><div class="stock-actions"><button class="mini" onclick="editStock('${s.id}')">编辑</button><button class="mini" onclick="consume('${s.id}')">登记消耗</button><button class="primary" onclick="addShopping('${s.id}')">去补货</button></div></div>`).join('');shoppingCount.textContent=data.shopping.length+' 项待办';shoppingList.innerHTML=data.shopping.length?data.shopping.map((s,i)=>row(s.name,`负责人 ${s.owner}${s.deadline?' · '+s.deadline+'前':''}`,`${badge(s.status)} <button class="mini" onclick="editShopping(${i})">编辑</button> <button class="mini" onclick="finishShopping(${i})">完成采购</button>`)).join(''):'<p>采购清单已完成</p>'}
function renderVisitors(){visitorList.innerHTML=data.visitors.map(v=>row(`${v.host}的${v.guest} · ${v.count}人`,`${v.id} · ${v.start}—${v.end} · ${v.stay}${v.conflict?' · '+v.conflict:''}`,`<div class="action-group">${badge(v.status)}<button class="mini" onclick="editVisitor('${v.id}')">编辑</button>${v.status==='待确认'?`<button class="mini" onclick="voteVisitor('${v.id}',false)">异议</button><button class="primary" onclick="voteVisitor('${v.id}',true)">同意</button>`:''}</div>`)).join('')}
function renderSafety(){safetyList.innerHTML=data.safety.map(s=>row(s.name,`预设回家时间 ${s.time}`,`<div class="action-group">${badge(s.status)}${s.status==='预计按时'?`<button class="mini" onclick="arriveHome('${s.name}')">确认到家</button>`:''}</div>`)).join('')}
function renderRules(){ruleList.innerHTML=data.rules.map(r=>row(r.title,`${r.id} · ${r.detail} · ${r.version||'v2.1'}`,`<div class="action-group">${badge(r.status)}<button class="mini" onclick="editRule('${r.id}')">修订</button><button class="mini" onclick="ruleHistory('${r.id}')">版本</button>${r.status.includes('待')?`<button class="mini" onclick="confirmRule('${r.id}')">赞成</button><button class="mini" onclick="rejectRule('${r.id}')">反对</button>`:''}</div>`)).join('')}
function renderLogs(){let type=logType?.value||'全部模块',q=(logSearch?.value||'').toLowerCase(),list=data.logs.filter(l=>(type==='全部模块'||l.type===type)&&(`${l.code}${l.action}${l.detail}${l.who}`.toLowerCase().includes(q)));logCount.textContent=list.length;logList.innerHTML=list.map(l=>`<div class="log"><b>${l.who} · ${l.action}</b> ${badge(l.type)}<div>${l.detail}</div><small>${l.time} · <span class="log-code">${l.code}</span></small></div>`).join('')}
function renderSettings(){weatherCity.textContent=data.preferences.city;memberList.innerHTML=data.members.map(m=>row(m.name,`${m.role} · ${m.room}`,currentUser==='小王'&&m.name!=='小王'?`<button class="mini" onclick="removeMember('${m.name}')">移出</button>`:badge('正常'))).join('')}
function audit(type,action,detail){let code=`${type==='账单'?'PAY':type==='任务'?'TSK':type==='物品'?'STK':type==='访客'?'VIS':type==='安全'?'SAFE':'RUL'}-${Date.now().toString().slice(-10)}`;data.logs.unshift({code,type,time:new Date().toLocaleString('zh-CN',{hour12:false}),who:currentUser||'访客',action,detail});save();renderAll();notify(action+'，已生成存档')}
function payBill(id){let b=data.bills.find(x=>x.id===id);modalForm('上传缴费凭证',field('实际金额','fAmount','number',b.amount)+`<div class="field"><label>凭证图片</label><input id="fProof" type="file" accept="image/*"></div>`+field('缴费渠道','fChannel','text','支付宝'),`confirmPay('${id}')`)}
function confirmPay(id){let b=data.bills.find(x=>x.id===id);b.amount=+fAmount.value;b.proof=fProof.files[0]?.name||'电子回单';b.status='已垫付';b.shares=data.members.map(m=>({name:m.name,amount:+(b.amount/data.members.length).toFixed(2),paid:m.name===currentUser}));closeModal();audit('账单','完成服务商缴费',`${b.name} ¥${b.amount}，凭证${b.proof}，已生成AA分摊`)}
function settleBill(id){let b=data.bills.find(x=>x.id===id);b.status='已结清';b.shares.forEach(s=>s.paid=true);audit('账单','完成室友内部结算',`${b.name} 全员已付款`)}
function billDetail(id){let b=data.bills.find(x=>x.id===id);modal.innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>${b.name} · 分摊明细</h2><div>${b.shares.map(s=>row(s.name,`应付 ¥${s.amount}`,`${badge(s.paid?'已付款':'待付款')} ${!s.paid?`<button class="mini" onclick="markShare('${id}','${s.name}')">标记付款</button>`:''}`)).join('')}</div>`;modalWrap.classList.add('open')}
function markShare(id,name){let b=data.bills.find(x=>x.id===id),s=b.shares.find(x=>x.name===name);s.paid=true;if(b.shares.every(x=>x.paid))b.status='已结清';closeModal();audit('账单','确认成员付款',`${name}完成${b.name}分摊款 ¥${s.amount}`)}
function editBill(id){let b=data.bills.find(x=>x.id===id);modalForm('编辑账单',field('账单名称','fName','text',b.name)+field('金额','fAmount','number',b.amount)+field('到期日期','fDate','date',b.due)+field('负责人','fOwner','text',b.payer)+field('提醒规则','fRemind','text',b.remind)+field('修改原因','fDetail','text','按实际账单调整'),`saveEditBill('${id}')`)}
function saveEditBill(id){let b=data.bills.find(x=>x.id===id),before=`${b.name} ¥${b.amount}`;b.name=fName.value;b.amount=+fAmount.value;b.due=fDate.value;b.payer=fOwner.value;b.remind=fRemind.value;b.shares=data.members.map(m=>({name:m.name,amount:+(b.amount/data.members.length).toFixed(2),paid:false}));closeModal();audit('账单','修改账单',`${before} → ${b.name} ¥${b.amount}，原因：${fDetail.value}`)}
function finishTask(id){let t=data.tasks.find(x=>x.id===id);modalForm('提交任务完成',`<div class="field full"><label>完成说明</label><textarea id="fDetail" rows="3">已按要求完成</textarea></div><div class="field full"><label>完成照片</label><input id="fProof" type="file" accept="image/*"></div>`,`confirmTask('${id}')`)}
function confirmTask(id){let t=data.tasks.find(x=>x.id===id);t.status='待验收';t.proof=fProof.files[0]?.name||'完成记录';closeModal();audit('任务','提交任务完成',`${t.name}，${fDetail.value}，等待室友验收`)}
function verifyTask(id){let t=data.tasks.find(x=>x.id===id);t.status='已验收';audit('任务','验收任务',`${t.name} 已完成并归档`)}
function swapTask(id){let t=data.tasks.find(x=>x.id===id);modalForm('申请调班',field('转交给','fOwner','text','小陈')+field('原因','fDetail','text','临时加班'),`confirmSwap('${id}')`)}
function confirmSwap(id){let t=data.tasks.find(x=>x.id===id),old=t.owner;t.owner=fOwner.value;t.status='待接收';closeModal();audit('任务','提交调班申请',`${t.name}由${old}转交${t.owner}，原因：${fDetail.value}`)}
function editTask(id){let t=data.tasks.find(x=>x.id===id);modalForm('编辑任务',field('任务名称','fName','text',t.name)+field('负责人','fOwner','text',t.owner)+field('日期','fDate','text',t.date)+field('截止时间','fTime','text',t.time)+field('修改原因','fDetail','text','排班调整'),`saveEditTask('${id}')`)}
function saveEditTask(id){let t=data.tasks.find(x=>x.id===id),before=`${t.name}/${t.owner}`;t.name=fName.value;t.owner=fOwner.value;t.date=fDate.value;t.time=fTime.value;closeModal();audit('任务','修改任务',`${before} → ${t.name}/${t.owner}，原因：${fDetail.value}`)}
function consume(id){let s=data.stock.find(x=>x.id===id);modalForm('登记物品消耗',field('消耗数量','fAmount','number','1')+field('使用人','fOwner','text',currentUser)+field('用途说明','fDetail','text','日常使用'),`confirmConsume('${id}')`)}
function confirmConsume(id){let s=data.stock.find(x=>x.id===id),amount=Math.max(1,+fAmount.value);s.qty=Math.max(0,s.qty-amount);closeModal();audit('物品','登记物品消耗',`${s.name} -${amount}${s.unit}，使用人${fOwner.value}，用途：${fDetail.value}，剩余${s.qty}${s.unit}`)}
function addShopping(id){let s=data.stock.find(x=>x.id===id);modalForm('创建补货任务',field('采购数量','fAmount','number',s.min*2)+field('负责人','fOwner','text',currentUser)+field('截止日期','fDate','date',new Date().toISOString().slice(0,10))+field('预计单价','fPrice','number','6'),`confirmShopping('${id}')`)}
function confirmShopping(id){let s=data.stock.find(x=>x.id===id),item={name:`${s.name} ${fAmount.value}${s.unit}`,owner:fOwner.value,status:'待采购',deadline:fDate.value,qty:+fAmount.value,stockId:id,estimate:+fPrice.value*fAmount.value};data.shopping.push(item);closeModal();audit('物品','创建补货任务',`${item.name}，负责人${item.owner}，预计¥${item.estimate}`)}
function editShopping(i){let item=data.shopping[i];modalForm('编辑采购任务',field('采购内容','fName','text',item.name)+field('负责人','fOwner','text',item.owner)+field('截止日期','fDate','date',item.deadline||'')+field('预计总价','fAmount','number',item.estimate||36),`saveShopping(${i})`)}
function saveShopping(i){let item=data.shopping[i],before=item.name;item.name=fName.value;item.owner=fOwner.value;item.deadline=fDate.value;item.estimate=+fAmount.value;closeModal();audit('物品','修改采购任务',`${before} → ${item.name}，预计¥${item.estimate}`)}
function finishShopping(i){let item=data.shopping[i];modalForm('完成采购并入账',field('实际支付金额','fAmount','number',item.estimate||36)+field('付款人','fOwner','text',currentUser)+field('实际购入数量','fQty','number',item.qty||6)+`<div class="field"><label>购物凭证</label><input id="fProof" type="file" accept="image/*"></div>`+field('参与分摊成员','fParticipants','text','小王,小林,小陈,阿杰')+field('分摊方式','fShare','text','平均分摊'),`confirmFinishShopping(${i})`)}
function confirmFinishShopping(i){let item=data.shopping[i],s=data.stock.find(x=>x.id===(item.stockId||'')||item.name.includes(x.name)),amount=+fAmount.value,qty=+fQty.value,proof=fProof.files[0]?.name||'购物小票',names=fParticipants.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);if(!names.length)return notify('请填写参与分摊成员');if(s)s.qty+=qty;data.shopping.splice(i,1);data.bills.unshift({id:'PAY-'+Date.now().toString().slice(-8),name:`采购${item.name}`,amount,due:new Date().toISOString().slice(0,10),payer:fOwner.value,status:'已垫付',repeat:'单次',remind:'即时',proof,shares:names.map(name=>({name,amount:+(amount/names.length).toFixed(2),paid:name===fOwner.value}))});closeModal();audit('物品','完成采购并生成账单',`${item.name}，实付¥${amount}，购入${qty}${s?.unit||'件'}，凭证${proof}，${names.join('、')}${fShare.value}`)}
function editStock(id){let s=data.stock.find(x=>x.id===id);modalForm('编辑公共物品',field('物品名称','fName','text',s.name)+field('当前库存','fAmount','number',s.qty)+field('单位','fUnit','text',s.unit)+field('安全库存','fMin','number',s.min)+field('调整原因','fDetail','text','盘点修正'),`saveEditStock('${id}')`)}
function saveEditStock(id){let s=data.stock.find(x=>x.id===id),before=`${s.name} ${s.qty}${s.unit}`;s.name=fName.value;s.qty=+fAmount.value;s.unit=fUnit.value;s.min=+fMin.value;closeModal();audit('物品','调整物品档案',`${before} → ${s.name} ${s.qty}${s.unit}，原因：${fDetail.value}`)}
function voteVisitor(id,ok){let v=data.visitors.find(x=>x.id===id);if(!ok){modalForm('提交访客异议',field('异议原因','fDetail','text','影响休息')+field('建议方案','fPlan','text','调整来访时间'),`confirmVisitorObjection('${id}')`);return}v.status='已同意';audit('访客','同意访客申请',`${v.host}的${v.guest}来访 · ${v.start}`)}
function confirmVisitorObjection(id){let v=data.visitors.find(x=>x.id===id);v.status='有异议';v.objection=fDetail.value;closeModal();audit('访客','提交访客异议',`${v.host}的${v.guest}来访，原因：${fDetail.value}，建议：${fPlan.value}`)}
function editVisitor(id){let v=data.visitors.find(x=>x.id===id);modalForm('编辑访客报备',field('访客称呼','fName','text',v.guest)+field('人数','fAmount','number',v.count)+field('到访时间','fDate','text',v.start)+field('离开时间','fEnd','text',v.end)+field('留宿情况','fStay','text',v.stay)+field('修改原因','fDetail','text','行程变化'),`saveEditVisitor('${id}')`)}
function saveEditVisitor(id){let v=data.visitors.find(x=>x.id===id),before=`${v.guest}/${v.start}`;v.guest=fName.value;v.count=+fAmount.value;v.start=fDate.value;v.end=fEnd.value;v.stay=fStay.value;v.status='待确认';closeModal();audit('访客','修改访客报备',`${before} → ${v.guest}/${v.start}，重新进入确认流程，原因：${fDetail.value}`)}
function arriveHome(name){name=currentUser||name;let s=data.safety.find(x=>x.name===name);if(!s)return;s.status='已到家';audit('安全','完成到家确认',`${name} 已安全到家`)}
function reportLate(){modalForm('晚归与不回报备',field('预计回家日期','fDate','date',new Date().toISOString().slice(0,10))+field('预计回家时间','fLateTime','time','00:00')+`<div class="field"><label>状态</label><select id="fLateType"><option>晚归</option><option>今晚不回</option><option>出差</option><option>回家过节</option></select></div>`+field('原因','fDetail','text','加班或聚餐')+`<div class="field full"><label>通知说明</label><input id="fNotice" value="请勿等待，回家后会确认到家"></div>`,"confirmLateReport()")}
function confirmLateReport(){let s=data.safety.find(x=>x.name===currentUser);if(!s)return;let type=fLateType.value;s.status=type==='晚归'?'已报备晚归':'今晚不回';s.time=type==='晚归'?fLateTime.value:'—';closeModal();audit('安全','提交'+type+'报备',`${currentUser} · ${fDate.value} · ${type==='晚归'?'预计'+fLateTime.value+'到家':'无需到家确认'} · 原因：${fDetail.value} · ${fNotice.value}`)}
function editSafety(){modalForm('到家提醒设置',field('工作日回家时间','fWork','time','23:00')+field('周末回家时间','fWeekend','time','23:30')+field('异常通知室友','fOwner','text','小林')+field('超时分钟','fDelay','number','30'),"saveSafety()")}
function saveSafety(){data.preferences.safetyTime=fWork.value;closeModal();audit('安全','修改到家提醒',`工作日${fWork.value}，超时${fDelay.value}分钟通知${fOwner.value}`)}
function confirmRule(id){let r=data.rules.find(x=>x.id===id);r.status='已生效';audit('公约','赞成公约提案',`${r.title}，已完成全员确认`)}
function rejectRule(id){let r=data.rules.find(x=>x.id===id);r.status='有异议';audit('公约','反对公约提案',`${r.title}，等待重新讨论`)}
function ruleHistory(id){let r=data.rules.find(x=>x.id===id);modal.innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>${r.title}</h2><div class="timeline"><div class="log"><b>${r.version||'v2.1'} 当前版本</b><div>${r.detail}</div><small>投票与生效记录完整保留</small></div><div class="log"><b>v2.0 历史版本</b><div>原始条款已归档，不可覆盖</div><small>2026-07-01 生效</small></div></div>`;modalWrap.classList.add('open')}
function editRule(id){let r=data.rules.find(x=>x.id===id);modalForm('修订公约',field('条款标题','fName','text',r.title)+`<div class="field full"><label>修订内容</label><textarea id="fDetail" rows="4">${r.detail}</textarea></div>`+field('修订原因','fReason','text','根据共同生活情况调整'),`saveEditRule('${id}')`)}
function saveEditRule(id){let r=data.rules.find(x=>x.id===id),oldVersion=r.version||'v2.1',parts=oldVersion.slice(1).split('.');r.version=`v${parts[0]}.${+parts[1]+1}`;r.title=fName.value;r.detail=fDetail.value;r.status='待全员确认';closeModal();audit('公约','提交公约新版本',`${oldVersion} → ${r.version}，原因：${fReason.value}；旧版本继续存档`)}
function modalForm(title,fields,submit){modal.innerHTML=`<button class="close" onclick="closeModal()">×</button><h2>${title}</h2><div class="form-grid">${fields}</div><div class="modal-footer"><button class="ghost" onclick="closeModal()">取消</button><button class="primary" onclick="${submit}">确认并留痕</button></div>`;modalWrap.classList.add('open')}
const field=(label,id,type='text',value='')=>`<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${value}" required></div>`;
function openBillModal(){modalForm('新建周期账单',field('账单名称','fName')+field('金额','fAmount','number')+field('缴费日期','fDate','date','2026-10-15')+field('负责人','fOwner','text','小王')+field('提醒规则','fRemind','text','提前7天、3天')+field('参与成员','fParticipants','text','小王,小林,小陈,阿杰')+field('分摊规则','fShare','text','平均分摊'),"createBill()")}
function createBill(){if(!fName.value||!fAmount.value)return notify('请填写账单名称和金额');let amount=+fAmount.value,names=fParticipants.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);if(!names.length)return notify('请填写参与成员');data.bills.unshift({id:'PAY-'+Date.now().toString().slice(-8),name:fName.value,amount,due:fDate.value,payer:fOwner.value,status:'待缴费',repeat:'每月',remind:fRemind.value,shares:names.map(name=>({name,amount:+(amount/names.length).toFixed(2),paid:false}))});closeModal();audit('账单','创建周期账单',`${fName.value} ¥${fAmount.value}，${names.join('、')}${fShare.value}`)}
function openTaskModal(){modalForm('新建生活任务',field('任务名称','fName')+field('负责人','fOwner','text','小王')+field('完成日期','fDate','date','2026-09-13')+field('截止时间','fTime','time','20:00'),"createTask()")}
function createTask(){data.tasks.unshift({id:'TSK-'+Date.now().toString().slice(-8),date:fDate.value,name:fName.value,owner:fOwner.value,time:fTime.value,status:'待接收'});closeModal();audit('任务','创建并指派任务',`${fName.value} · ${fOwner.value}负责`)}
function openStockModal(){modalForm('登记公共物品',field('物品名称','fName')+field('当前数量','fAmount','number','1')+field('单位','fUnit','text','件')+field('安全库存','fMin','number','2'),"createStock()")}
function createStock(){data.stock.push({id:'STK-'+Date.now().toString().slice(-6),icon:'📦',name:fName.value,qty:+fAmount.value,unit:fUnit.value,min:+fMin.value});closeModal();audit('物品','登记公共物品',`${fName.value} ${fAmount.value}${fUnit.value}`)}
function openVisitorModal(){modalForm('发起访客报备',field('访客称呼','fName')+field('人数','fAmount','number','1')+field('到访时间','fDate','datetime-local')+field('预计离开','fEnd','datetime-local')+field('是否留宿','fStay','text','不留宿')+field('使用区域','fArea','text','客厅'),"createVisitor()")}
function createVisitor(){data.visitors.unshift({id:'VIS-'+Date.now().toString().slice(-8),host:'小王',guest:fName.value,count:+fAmount.value,start:fDate.value,end:fEnd.value,stay:fStay.value,status:'待确认',conflict:'系统未发现明显冲突'});closeModal();audit('访客','发起访客报备',`${fName.value} ${fAmount.value}人 · ${fDate.value}`)}
function openRuleModal(){modalForm('发起公约提案',field('提案标题','fName')+`<div class="field full"><label>具体内容</label><textarea id="fDetail" rows="4"></textarea></div>`+field('计划生效日','fDate','date','2026-09-20'),"createRule()")}
function createRule(){data.rules.push({id:'RUL-'+Date.now().toString().slice(-6),title:fName.value,detail:fDetail.value,status:'待全员确认',version:'v1.0'});closeModal();audit('公约','发起公约提案',`${fName.value}，计划${fDate.value}生效`)}
function openMemberModal(){if(currentUser!=='小王')return notify('仅房屋管理员可邀请成员');modalForm('邀请新成员',field('成员姓名','fName')+field('房间','fRoom','text','次卧')+field('入住日期','fDate','date','2026-09-15')+field('邀请码有效期','fDelay','number','24'),"createMember()")}
function createMember(){data.members.push({name:fName.value,role:'普通成员',room:fRoom.value});closeModal();audit('公约','邀请合租成员',`${fName.value} · ${fRoom.value} · 邀请码24小时有效`)}
function removeMember(name){if(!confirm(`确认将${name}移出合租空间？历史记录仍会保留。`))return;data.members=data.members.filter(m=>m.name!==name);audit('公约','移出合租成员',`${name}已移出，历史档案继续保留`)}
function editPreferences(){modalForm('生活提醒设置',field('天气城市','fCity','text',data.preferences.city)+field('缴费提醒','fBill','text',data.preferences.billReminder)+field('低库存阈值','fMin','number','3')+field('免打扰开始','fQuiet','time','23:00'),"savePreferences()")}
function savePreferences(){data.preferences.city=fCity.value;data.preferences.billReminder=fBill.value;closeModal();audit('安全','修改生活提醒',`${fCity.value}天气，缴费${fBill.value}，23:00后免打扰`)}
function closeModal(e){if(!e||e.target===modalWrap||e.target.classList.contains('close'))modalWrap.classList.remove('open')}
function notify(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function exportLogs(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data.logs,null,2)],{type:'application/json'}));a.download='同住操作档案.json';a.click();audit('公约','导出操作档案','导出全部可追溯记录')}
function resetDemo(){if(confirm('确定恢复初始演示数据？')){localStorage.removeItem('roomie_mvp_v2');location.reload()}}
init();
